# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict_sign.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12predict_sign.proto\x12\x07predict\"2\n\rSequenceInput\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x11\n\tclient_id\x18\x02 \x01(\t\"N\n\rPredictResult\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0epredicted_word\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x32\x43\n\x06SignAI\x12\x39\n\x07Predict\x12\x16.predict.SequenceInput\x1a\x16.predict.PredictResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_sign_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEQUENCEINPUT._serialized_start=31
  _SEQUENCEINPUT._serialized_end=81
  _PREDICTRESULT._serialized_start=83
  _PREDICTRESULT._serialized_end=161
  _SIGNAI._serialized_start=163
  _SIGNAI._serialized_end=230
# @@protoc_insertion_point(module_scope)
